name: Trigger Parent CI

on:
  push:
    branches:
      - main # or your relevant branch

jobs:
  notify-parent:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger parent repo
        run: |
          curl -X POST https://api.github.com/repos/Nimra-stellarstack/parent-repo/dispatches \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.PARENT_REPO_TOKEN }}" \
          -d '{"event_type": "child-updated"}'
